WebApi/Controllers/ViewMessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApi.ViewModels;

namespace WebApi.Controllers
{
    public class ViewMessagesController : Controller
    {
        Orchestration.Messages actions = new Orchestration.Messages();

        // GET: ViewMessages
        public ActionResult Index()
        {
            // Generate view model to display page
            var viewModel = new ViewModels.MessagesViewModel();
            // Generate page data
            var messages = actions.Read();

            return View(viewModel.GenerateViewModel(messages));
        }

        public ActionResult Create() {

            var viewModel = new WebApi.ViewModels.MessagesCreateViewModel();

            return View(viewModel);
        }

        public ActionResult Amend(int id) {

            var viewModel = new WebApi.ViewModels.MessagesAmendViewModel(id);

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(MessagesCreateViewModel messageVM )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Domain.Message message = AutoMapper.Mapper.Map<Domain.Message>(messageVM);

                    if (actions.CreateMessage(message).IsValid)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View(messageVM);
            }
            catch (Exception ex)
            {
                return View(messageVM);
            }
        }

        [HttpPost]
        public ActionResult Amend(MessagesAmendViewModel messageVM )
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Domain.Message message = AutoMapper.Mapper.Map<Domain.Message>(messageVM);

                    if (actions.AmendMessage(message).IsValid)
                    {
                        return RedirectToAction("Index");
                    }
                }
                return View(messageVM);
            }
            catch(Exception ex)
            {
                return View(messageVM);
            }
        }

        public ActionResult Cancel() => RedirectToAction("Index");
    }
}

WebApi/Views/ViewMessages/Amend.cshtml
@model WebApi.ViewModels.MessagesAmendViewModel

@{
    ViewBag.Title = "Amend";
}

<h2>Amend</h2>


@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.messageID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.messageID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.messageID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startShowing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startShowing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startShowing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numberOfDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numberOfDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numberOfDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.applicationsList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.selectedApplication, Model.applicationsList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.applicationsList, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <br />

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Amend" class="btn btn-default" />
            @Html.ActionLink("Cancel","Cancel", "ViewMessages",null, new { @class = "btn btn-default" })
        </div>
    </div>

    <hr />
}

WebApi/Views/ViewMessages/Create.cshtml
@model WebApi.ViewModels.MessagesCreateViewModel

@{
    ViewBag.Title = "CreateMessage";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control", @maxlength = "250" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startShowing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startShowing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startShowing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numberOfDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numberOfDays, new { htmlAttributes = new { @class = "form-control", @maxlength = "2" } })
                @Html.ValidationMessageFor(model => model.numberOfDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.applicationsList, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.selectedApplication, Model.applicationsList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.applicationsList, "", new { @class = "text-danger" })
            </div>
        </div>
       
    </div>

    <br />

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Create" class="btn btn-default" />
            @Html.ActionLink("Cancel", "Cancel", "ViewMessages", null, new { @class = "btn btn-default" })
        </div>
    </div>

    <hr />
}

WebApi/Views/ViewMessages/Index.cshtml
@model WebApi.ViewModels.MessagesViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Messages</h2>


<div class="row">
    <div class="col-md-12">
        <span class="pull-right">
            @Html.ActionLink("Create", "Create", "ViewMessages", null , new { @class = "btn btn-default" })
        </span>
    </div>
</div>

<br />

<div class="row">
    <div class="col-md-12">
        <table id="TableOfSystems" class="table">
            <tr>
                <th>Message</th>
                <th>Show Date</th>
                <th>Show for (days)</th>
                <th class="text-center">Active</th>
            </tr>
            @foreach (var item in Model.view)
            {
                <tr id="@item.messageID" 
                    class="@item.tableRowDisplay @item.tableActiveTextDisplay"
                    onclick="location.href = '@(Url.Action("Amend","ViewMessages", new { Id = item.messageID }) )' ">
                    <td>@item.text</td>
                    <td>@item.showDate</td>
                    <td>@item.numberOfDays</td>
                    <td id="ActiveMessage" class="text-center" >@item.tableActiveText</td>
                </tr>
            }
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <span class="pull-right">Created : @Model.pageCreatedAt</span>
    </div>
</div>